### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by eike-hass** [iota-community/iota-wiki-cli#3]
We should setup a proper release to the npm registry to support version constrains in consuming projects.

**Comment by jlvandenhout** [comment]
Do we have an NPM account for the community repo or something so we can do this? Currently checksum verification fails for Yarn 2+ Git installs (yarnpkg/berry#2399), which fails our CI build on the Wiki. I think this would be solved by publishing it.

**Comment by eike-hass** [comment]
@jlvandenhout I don't think it exists ATM. I also strongly believe it would help to clean things up and manage nicely. Can you maybe get in touch with some community devs and try to figure this out?
Did you find a work-around for the CI? I assume the problem is the `prepack` script leading to different results in different environments.

**Comment by jlvandenhout** [comment]
That's exactly it probably. The only workarounds are to either not verify checksums at all or update them during install and have a mutable lock file, which both are not ideal from a security and integrity perspective. @Dr-Electron had the suggestion that creating a package artefact with a GitHub action could be an intermediate solution we could try without having to publish to npm.

**Comment by eike-hass** [comment]
I think an artifact has no advantage over copying a zip over, since it won't update anyways and its an install from zip/tar in both cases. [GitHub Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry) as an alternative registry might an option, but it probably requires similar effort as npm for setting up CI and governance.

**Comment by jlvandenhout** [comment]
We could release the packed version right? So it won't need to run those pre and post scripts again. Would basically be the same thing you'd send to npm.

**Comment by jlvandenhout** [comment]
But yeah makes sense to just do this properly. I'll ask Antonio if we have an npm account already.

**Comment by eike-hass** [comment]
> We could release the packed version right? So it won't need to run those pre and post scripts again. Would basically be the same thing you'd send to npm.

yes, but from a npm install perspective it doesn't make a difference, since npm has no concept oh GitHub release AFAIK
